{application,netapp,
             [{description,"An OTP application"},
              {vsn,"0.1.0"},
              {registered,[]},
              {mod,{netapp_app,[]}},
              {applications,[kernel,stdlib,lager]},
              {env,[]},
              {modules,[dhtcp,dhtcp_acceptor,dhtcp_conn,dhtcp_conn_sup,
                        dhtcp_sup,netapp_app,netapp_sup,tcp_test]},
              {licenses,["Apache 2.0"]},
              {links,[]}]}.
